---
ID: "81506539-e7f5-4044-8182-a3d351a9db0d"
Parent: "0ceeaade-7eb1-4930-a94b-cee63fc26c3d"
Template: "0ceeaade-7eb1-4930-a94b-cee63fc26c3d"
Path: /sitecore/templates/Project/StarterSites/Blog Components/Rendering Parameters/BlogList Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ea4938c8-100c-4a6d-b7b0-dd492c7a14f9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250228T125830Z
