---
ID: "760da525-35e5-4208-8dc0-31244f6528ee"
Parent: "5c4c9e53-b627-4a13-b6ea-9ac693771a8f"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/StarterSites/nextjs-starter/Presentation/Headless Variants/BlogComments/Default"
BranchID: "e27e7b79-c8af-41b0-a5ba-471be5fd090f"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{79F6CBA5-DF47-4E5D-9736-6271B3CB7256}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250302T192037Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d321fd92-ebbf-4f09-a5ad-4f6987dfda9a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250302T192037Z
