---
ID: "5cfe0661-e947-42bb-916d-4a651e3ad69c"
Parent: "caab2dd9-3e15-43bf-bd47-17a50aaa9117"
Template: "caab2dd9-3e15-43bf-bd47-17a50aaa9117"
Path: /sitecore/templates/Project/StarterSites/Blog Components/Rendering Parameters/BlogListingContainer Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "566c4e66-977a-4873-9be0-3079e93a6e77"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250303T033657Z
