---
ID: "22a36dbc-6440-4489-a8fa-f40eb171d596"
Parent: "4854cba8-246e-47c8-829e-4e7460473a42"
Template: "4854cba8-246e-47c8-829e-4e7460473a42"
Path: /sitecore/templates/Project/StarterSites/Blog Components/Rendering Parameters/RelatedBlogs Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a34750ed-5f83-4c42-ab85-958c0be1d97e"
