---
ID: "22a36dbc-6440-4489-a8fa-f40eb171d596"
Parent: "4854cba8-246e-47c8-829e-4e7460473a42"
Template: "4854cba8-246e-47c8-829e-4e7460473a42"
Path: /sitecore/templates/Project/StarterSites/Blog Components/Rendering Parameters/RelatedBlogs Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a34750ed-5f83-4c42-ab85-958c0be1d97e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250228T125959Z
