---
ID: "b4261710-e86c-4ac8-a363-b4fffa507cf8"
Parent: "33f89900-d90a-4061-9382-52faabfc6fbf"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/StarterSites/nextjs-starter/Presentation/Headless Variants/PageContent/Default"
BranchID: "5abe3762-5a9c-4710-9730-bb302e90fd13"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{E9B59BC9-57CB-43AC-8FD7-F9A676B0C46F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250222T175140Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a8d45093-6fba-42fa-83fc-93518e891444"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250222T175140Z
