---
ID: "af17be70-6373-45ed-979d-59ae7390496a"
Parent: "41627d2a-a29d-49bb-a7b6-f058daf66690"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/StarterSites/nextjs-starter/Presentation/Headless Variants/RelatedBlogs/Default"
BranchID: "8c117dc7-b824-49aa-bb8e-a5aeaaf48b36"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{524CB0D6-AA15-47D0-963D-E9EDB923C158}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250302T192038Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "41adac0c-1e43-46ae-b81b-a3d9dd18018b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250302T192038Z
