---
ID: "52e360d8-6fc0-4ae9-9874-6ea774b78aa4"
Parent: "16e3d160-945d-4845-8c97-a2531206ecc2"
Template: "1105b8f8-1e00-426b-bf1f-c840742d827b"
Path: /sitecore/content/PlaySites/BasicCompany/Presentation/Page Designs/Default
SharedFields:
- ID: "0966b999-0d0e-4278-acc9-9da69d461fe6"
  Hint: PartialDesigns
  Value: "{FE3ABFC1-FF6E-4B82-9A76-8DEB3DEEEAAE}|{CA770E14-176D-4FE1-A82F-AAF4977CB2E9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250222T173841Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "88f4aad5-06be-4714-8d24-368d8c2b24a9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ssebastianarokya@gmail.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250222T173847Z
